<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">mergeDocumentLists</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7CklEYXRhW10gbGlzdDEgPSBJRGF0YVV0aWwuZ2V0SURhdGFBcnJheShwaXBlbGlu
ZUN1cnNvciwgImxpc3QxIik7CklEYXRhW10gbGlzdDIgPSBJRGF0YVV0aWwuZ2V0SURhdGFBcnJh
eShwaXBlbGluZUN1cnNvciwgImxpc3QyIik7CgovLyBwcm9jZXNzCgpJRGF0YVtdIG1lcmdlZExp
c3QgPSBsaXN0MTsKCmlmIChsaXN0MSAhPSBudWxsKSB7CgkKCWlmIChsaXN0MiAhPSBudWxsKSB7
CgkJCgkJbWVyZ2VkTGlzdCA9IG5ldyBJRGF0YVtsaXN0MS5sZW5ndGggKyBsaXN0Mi5sZW5ndGhd
OwoJCQoJCWZvciAoaW50IGkgPSAwOyBpIDwgbGlzdDEubGVuZ3RoO2krKykgewoJCQltZXJnZWRM
aXN0W2ldID0gbGlzdDFbaV07CgkJfQoJCQoJCWZvciAoaW50IGkgPSAwOyBpIDwgbGlzdDIubGVu
Z3RoO2krKykgewoJCQltZXJnZWRMaXN0W2xpc3QxLmxlbmd0aCArIGldID0gbGlzdDJbaV07CgkJ
fQoJfQp9IGVsc2UgewoJbWVyZ2VkTGlzdCA9IGxpc3QyOwp9Ci8vIHBpcGVsaW5lIG91dAoKSURh
dGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgIm1lcmdlZExpc3QiLCBtZXJnZWRMaXN0KTsKcGlw
ZWxpbmVDdXJzb3IuZGVzdHJveSgpOwoKCQ==</value>
</Values>
